TotalHRInsight/TotalHRInsight/Models/ErrorDeleteModel.cs
namespace TotalHRInsight.Models
{
    public class ErrorDeleteModel
    {
        public string Message { get; set; }
        public string RequestId { get; set; }
        public string Details { get; set; }
        public bool ShowDetails => !string.IsNullOrEmpty(Details);
    }
}

TotalHRInsight/TotalHRInsight/Controllers/EstadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TotalHRInsight.DAL;

namespace TotalHRInsight.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class EstadosController : Controller
    {
        private readonly TotalHRInsightDbContext _context;

        public EstadosController(TotalHRInsightDbContext context)
        {
            _context = context;
        }

        // GET: Estados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estados.ToListAsync());
        }

        // GET: Estados/Details/5
        public async Task<IActionResult> Details(int? IdEstado)
        {
            if (IdEstado == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.IdEstado == IdEstado);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // GET: Estados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEstado,EstadoSolicitud")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Edit/5
        public async Task<IActionResult> Edit(int? IdEstado)
        {
            if (IdEstado == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados.FindAsync(IdEstado);
            if (estado == null)
            {
                return NotFound();
            }
            return View(estado);
        }

        // POST: Estados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdEstado, [Bind("IdEstado,EstadoSolicitud")] Estado estado)
        {
            if (IdEstado != estado.IdEstado)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoExists(estado.IdEstado))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Delete/5
        public async Task<IActionResult> Delete(int? IdEstado)
        {
            if (IdEstado == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.IdEstado == IdEstado);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // POST: Estados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int IdEstado)
        {
            var estado = await _context.Estados.FindAsync(IdEstado);
            if (estado != null)
            {
                _context.Estados.Remove(estado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoExists(int IdEstado)
        {
            return _context.Estados.Any(e => e.IdEstado == IdEstado);
        }
    }
}

TotalHRInsight/TotalHRInsight/Controllers/GastosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TotalHRInsight.DAL;

namespace TotalHRInsight.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class GastosController : Controller
    {
        private readonly TotalHRInsightDbContext _context;

        public GastosController(TotalHRInsightDbContext context)
        {
            _context = context;
        }

        // GET: Gastos
        public async Task<IActionResult> Index()
        {
            var totalHRInsightDbContext = _context.Gastos.Include(g => g.CierreCaja).Include(g => g.TipoGasto);
            return View(await totalHRInsightDbContext.ToListAsync());
        }

        // GET: Gastos/Details/5
        public async Task<IActionResult> Details(int? IdGasto)
        {
            if (IdGasto == null)
            {
                return NotFound();
            }

            var gasto = await _context.Gastos
                .Include(g => g.CierreCaja)
                .Include(g => g.TipoGasto)
                .FirstOrDefaultAsync(m => m.IdGasto == IdGasto);
            if (gasto == null)
            {
                return NotFound();
            }

            return View(gasto);
        }

        // GET: Gastos/Create
        // GET: Gastos/Create
        public IActionResult Create()
        {
            ViewData["SucursalId"] = new SelectList(_context.Sucursales, "IdSucursal", "NombreSucursal");
            ViewData["TipoGastoId"] = new SelectList(_context.TipoGastos, "IdTipoGasto", "NombreGasto");
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetCierresBySucursal(int sucursalId)
        {
            var cierres = await _context.CierreCajas
                .Where(c => c.SucursalId == sucursalId)
                .Select(c => new
                {
                    c.IdCierraCaja,
                    c.Fecha
                })
                .ToListAsync();

            return Json(cierres);
        }


        // POST: Gastos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdGasto,Fecha,TipoGastoId,MontoGasto,CierreId")] Gasto gasto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gasto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CierreId"] = new SelectList(_context.CierreCajas, "IdCierraCaja", "Fecha", gasto.CierreId);
            ViewData["TipoGastoId"] = new SelectList(_context.TipoGastos, "IdTipoGasto", "NombreGasto", gasto.TipoGastoId);
            return View(gasto);
        }



        // GET: Gastos/Edit/5
        public async Task<IActionResult> Edit(int? IdGasto)
        {
            if (IdGasto == null)
            {
                return NotFound();
            }

            var gasto = await _context.Gastos.FindAsync(IdGasto);
            if (gasto == null)
            {
                return NotFound();
            }
            ViewData["CierreId"] = new SelectList(_context.CierreCajas, "IdCierraCaja", "Fecha", gasto.CierreId);
            ViewData["TipoGastoId"] = new SelectList(_context.TipoGastos, "IdTipoGasto", "NombreGasto", gasto.TipoGastoId);
            return View(gasto);
        }

        // POST: Gastos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdGasto, [Bind("IdGasto,Fecha,TipoGastoId,MontoGasto,CierreId")] Gasto gasto)
        {
            if (IdGasto != gasto.IdGasto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gasto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GastoExists(gasto.IdGasto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CierreId"] = new SelectList(_context.CierreCajas, "IdCierraCaja", "Fecha", gasto.CierreId);
            ViewData["TipoGastoId"] = new SelectList(_context.TipoGastos, "IdTipoGasto", "NombreGasto", gasto.TipoGastoId);
            return View(gasto);
        }

        // GET: Gastos/Delete/5
        public async Task<IActionResult> Delete(int? IdGasto)
        {
            if (IdGasto == null)
            {
                return NotFound();
            }

            var gasto = await _context.Gastos
                .Include(g => g.CierreCaja)
                .Include(g => g.TipoGasto)
                .FirstOrDefaultAsync(m => m.IdGasto == IdGasto);
            if (gasto == null)
            {
                return NotFound();
            }

            return View(gasto);
        }

        // POST: Gastos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int IdGasto)
        {
            var gasto = await _context.Gastos.FindAsync(IdGasto);
            if (gasto != null)
            {
                _context.Gastos.Remove(gasto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GastoExists(int id)
        {
            return _context.Gastos.Any(e => e.IdGasto == id);
        }
    }
}

TotalHRInsight/TotalHRInsight/Controllers/MedidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TotalHRInsight.DAL;

namespace TotalHRInsight.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class MedidasController : Controller
	{
		private readonly TotalHRInsightDbContext _context;

		public MedidasController(TotalHRInsightDbContext context)
		{
			_context = context;
		}

		// GET: Medidas
		public async Task<IActionResult> Index()
		{
			return View(await _context.Medidas.ToListAsync());
		}

		// GET: Medidas/Details/5
		public async Task<IActionResult> Details(int? IdMedida)
		{
			if (IdMedida == null)
			{
				return NotFound();
			}

			var medida = await _context.Medidas
				.FirstOrDefaultAsync(m => m.IdMedida == IdMedida);
			if (medida == null)
			{
				return NotFound();
			}

			return View(medida);
		}

		// GET: Medidas/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Medidas/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("IdMedida,NombreMedida")] Medida medida)
		{
			if (ModelState.IsValid)
			{
				// Normalizar el nombre de la medida para comparar
				string nombreMedidaNormalizado = medida.NombreMedida.Trim().ToLower().Replace(" ", "");

				// Verificar si ya existe una medida con el mismo nombre normalizado
				bool medidaExiste = _context.Medidas
					.Any(m => m.NombreMedida.Trim().ToLower().Replace(" ", "") == nombreMedidaNormalizado);

				if (medidaExiste)
				{
					ModelState.AddModelError("NombreMedida", "La medida ya existe en la base de datos.");
				}
				else
				{
					_context.Add(medida);
					await _context.SaveChangesAsync();
					return RedirectToAction(nameof(Index));
				}
			}
			return View(medida);
		}

		// GET: Medidas/Edit/5
		public async Task<IActionResult> Edit(int? IdMedida)
		{
			if (IdMedida == null)
			{
				return NotFound();
			}

			var medida = await _context.Medidas.FindAsync(IdMedida);
			if (medida == null)
			{
				return NotFound();
			}
			return View(medida);
		}

		// POST: Medidas/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int IdMedida, [Bind("IdMedida,NombreMedida")] Medida medida)
		{
			if (IdMedida != medida.IdMedida)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(medida);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!MedidaExists(medida.IdMedida))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(medida);
		}

		// GET: Medidas/Delete/5
		public async Task<IActionResult> Delete(int? IdMedida)
		{
			if (IdMedida == null)
			{
				return NotFound();
			}

			var medida = await _context.Medidas
				.FirstOrDefaultAsync(m => m.IdMedida == IdMedida);
			if (medida == null)
			{
				return NotFound();
			}

			return View(medida);
		}

		// POST: Medidas/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int IdMedida)
		{
			var medida = await _context.Medidas.FindAsync(IdMedida);
			if (medida != null)
			{
				_context.Medidas.Remove(medida);
				await _context.SaveChangesAsync();
			}
			return RedirectToAction(nameof(Index));
		}

		private bool MedidaExists(int IdMedida)
		{
			return _context.Medidas.Any(e => e.IdMedida == IdMedida);
		}
	}
}

TotalHRInsight/TotalHRInsight/Views/Shared/ErrorDeleteModel.cshtml
@model TotalHRInsight.Models.ErrorDeleteModel
@{
    ViewData["Title"] = "Error";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-danger shadow">
                <div class="card-header bg-danger text-white">
                    <h3 class="card-title mb-0">
                        <i class="bi bi-exclamation-triangle-fill me-2"></i>Error
                    </h3>
                </div>
                <div class="card-body">
                    <div class="text-center mb-4">
                        <h4>@Model.Message</h4>
                        @if (Model.ShowDetails)
                        {
                            <div class="alert alert-warning mt-3">
                                <small class="text-muted">Detalles técnicos:</small><br />
                                @Model.Details
                            </div>
                        }
                        <div class="text-muted small mt-2">
                            ID de Referencia: @Model.RequestId
                        </div>
                    </div>
                    <div class="text-center">
                        <a asp-controller="Productos" asp-action="Index" class="btn btn-primary">
                            <i class="bi bi-arrow-left-circle me-2"></i>Volver al listado
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TotalHRInsight/TotalHRInsight/Views/Shared/_BarraNavegacion.cshtml
<header class="main-header">
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container-fluid">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <!-- Botones de acción principales -->
                <div class="header-actions">
                    <button class="header-btn" id="refreshButton" onclick="location.reload();">
                        <i class="bi bi-arrow-clockwise"></i>
                        <span>Refrescar</span>
                    </button>

                    <button class="header-btn" id="backButton" onclick="window.history.back();">
                        <i class="bi bi-arrow-left"></i>
                        <span>Volver</span>
                    </button>
                </div>

                <!-- Perfil de usuario y acciones -->
                <div class="user-profile">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>
</header>

TotalHRInsight/TotalHRInsight/Views/Shared/_HeaderPartial.cshtml
<div class="main-container">
	<!-- Sidebar -->
	<aside class="sidebar" aria-label="Menú de Navegación">
		<!-- Encabezado del Sidebar -->
		<header class="sidebar-header d-flex align-items-center justify-content-end">
			<img src="https://firebasestorage.googleapis.com/v0/b/empanatica-fc24c.appspot.com/o/Empana-tica_Logo.png?alt=media&token=6255cf42-233f-43cb-ba74-5ee325d25901"
				 class="img-fluid"
				 style="max-width: 35%;"
				 alt="Logo de Empana-tica">
			<h1 class="m-4">TotalHR Insight</h1>
		</header>

		<!-- Separador -->
		<hr>

		<!-- Menú de Navegación -->
		<nav class="sidebar-menu" role="navigation" aria-label="Menú Principal">
			<div class="menu-scroll">
				<!-- Enlace de Menú Principal -->
				<div class="menu-item">
					<a asp-area="" asp-controller="Asistencias" asp-action="Index" class="menu-link  link-dark">
						<span class="text-gray-600">
						<i class="bi bi-hand-thumbs-up"></i> Asistencia
						</span>
					</a>
				</div>

				<!-- Otro Enlace de Menú Principal -->
				<div class="menu-item">
					<a asp-area="" asp-controller="Pedidos" asp-action="Index" class="menu-link link-dark">
						<i class="bi bi-cart icon"></i> Pedidos
					</a>
				</div>

				<div class="menu-item">
					<a asp-area="" asp-controller="Pedidos" asp-action="Index" class="menu-link link-dark">
						<i class="bi bi-file-earmark-excel icon"></i> Devoluciones
					</a>
				</div>

				<div class="menu-item">
					<a asp-area="" asp-controller="Pedidos" asp-action="Devolucion" class="menu-link link-dark">
						<i class="bi bi-shop-window icon"></i> Sucursales
					</a>
				</div>

				<!-- Más Elementos del Menú -->
				<div class="menu-item">
					<a asp-area="" asp-controller="Admin" asp-action="Index" class="menu-link link-dark">
						<i class="bi bi-person-badge icon"></i> Usuarios
					</a>
				</div>

				<!-- Menú con Submenús -->
				<div class="menu-item">
					<button class="menu-link text-green-500" aria-expanded="false" aria-controls="inventario-submenu" onclick="toggleSubMenu('inventario-submenu')">
						<i class="bi bi-box-seam icon"></i>
						<span>Inventario</span>
						<i class="bi bi-chevron-down ms-auto"></i>
					</button>
					<!-- Submenú -->
					<ul class="submenu" id="inventario-submenu" role="menu">
						<li>
							<a asp-area="" asp-controller="Inventarios" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-boxes icon"></i> Ver Stock
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Productos" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-tags icon"></i>Productos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Proveedors" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-people icon"></i> Proveedores
							</a>
						</li>
					</ul>
				</div>

				<!-- Otro Menú con Submenús -->
				<div class="menu-item">
					<button class="menu-link text-red-500" aria-expanded="false" aria-controls="planilla-submenu" onclick="toggleSubMenu('planilla-submenu')">
						<i class="bi bi-person-bounding-box icon"></i>
						<span>Personal RH</span>
						<i class="bi bi-chevron-down ms-auto"></i>
					</button>
					<!-- Submenú -->
					<ul class="submenu" id="planilla-submenu" role="menu">
						<li>
							<a asp-area="" asp-controller="Deduccions" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-wallet icon"></i> Deducciones
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Permisoes" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-paperclip icon"></i> Permisos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Salarios" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-cash-coin icon"></i> Salarios
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Planillas" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-calendar icon"></i> Planilla
							</a>
						</li>
					</ul>
				</div>

				<!-- Otro Menú con Submenús -->
				<div class="menu-item">
					<button class="menu-link text-red-500" aria-expanded="false" aria-controls="informes-submenu" onclick="toggleSubMenu('informes-submenu')">
						<i class="bi bi-bank icon"></i>
						<span>Contable</span>
						<i class="bi bi-chevron-down ms-auto"></i>
					</button>
					<!-- Submenú -->
					<ul class="submenu" id="informes-submenu" role="menu">
						<li>
							<a asp-area="" asp-controller="Ingresos" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-graph-up-arrow icon"></i> Ingresos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Gastos" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-graph-down-arrow icon"></i> Gastos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="CierreCajas" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-piggy-bank icon"></i> Cierres
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Ingresos" asp-action="ResumenFinanciero" class="submenu-link link-dark ">
								<i class="bi bi-flag icon"></i> Reporte
							</a>
						</li>
					</ul>
				</div>
				<div class="menu-item">
					<button class="menu-link text-red-500" aria-expanded="false" aria-controls="ajustes-submenu" onclick="toggleSubMenu('ajustes-submenu')">
						<i class="bi bi-wrench-adjustable-circle icon"></i>
						<span>Ajustes</span>
						<i class="bi bi-chevron-down ms-auto"></i>
					</button>
					<!-- Submenú -->
					<ul class="submenu" id="ajustes-submenu" role="menu">
						<li>
							<a asp-area="" asp-controller="Estados" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-slash-circle icon"></i> Estados
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Medidas" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-box-arrow-up-right icon"></i> Medidas
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="TipoDeduccions" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-clipboard-data icon"></i> Deducciones
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="TipoPermiso" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-stickies icon"></i> Tipos permisos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="TipoIngresos" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-currency-pound icon"></i> Tipos ingresos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="TipoGastos" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-currency-dollar icon"></i> Tipos gastos
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Categorias" asp-action="Index" class="submenu-link link-dark">
								<i class="bi bi-bookmark icon"></i> Categorias
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- Separador -->
		<hr>

		<!-- Pie de Página del Sidebar -->
		<footer class="sidebar-footer">			
			<a asp-area="" asp-controller="Home" asp-action="Privacy" class="menu-link link-dark">
				 Sobre Nosotros
			</a>
			<a asp-area="" asp-controller="Home" asp-action="Index" class="menu-link link-dark">
				TotalHRInsight
			</a>
			<span>&copy; 2024</span>
		</footer>
	</aside>

TotalHRInsight/TotalHRInsight/Views/Shared/_LoaderModal.cshtml
<!-- Views/Shared/_LoaderModal.cshtml -->
<div class="modal fade" id="loaderModal" tabindex="-1" aria-labelledby="loaderModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="spinner-border text-danger" role="status">
                    <span class="visually-hidden">Cargando...</span>
                </div>
                <p class="mt-3">Por favor, espera...</p>
            </div>
        </div>
    </div>
</div>